#%RAML 1.0
types:
  ErrorViewModel:
    type: !include types/ErrorViewModel.raml
    additionalProperties: false
  ValidationErrorsViewModel:
    type: object
    additionalProperties: false
    properties:
      errorCode?:
        type: number
        format: int32
      errorMessages?:
        type: errorMessages | nil
  GetTodoViewModel:
    type: !include types/GetTodoViewModel.raml
    additionalProperties: false
  data:
    type: array
    items: GetTodoViewModel
  CommandResultViewModel:
    type: object
    additionalProperties: false
    properties:
      id?:
        type: id | nil
  GetTodoViewModelPagedResultViewModel:
    type: object
    additionalProperties: false
    properties:
      count:
        type: number
        format: int32
      data:
        type: array
        items: !include types/GetTodoViewModel.raml
  ValidationErrorViewModel:
    type: object
    additionalProperties: false
    properties:
      field?:
        type: string | nil
      message?:
        type: string | nil
  id:
    type: any
  CreateTodoViewModel:
    type: object
    additionalProperties: false
    properties:
      id?:
        type: string
      completed?:
        type: boolean
      order?:
        type: number
        format: int32
      title?:
        type: string | nil
      url?:
        type: string | nil
  order:
    type: number
    format: int32
  GetTodoByIdViewModel:
    type: object
    additionalProperties: false
    properties:
      id?:
        type: string
      completed?:
        type: boolean
      order?:
        type: number
        format: int32
      title?:
        type: string | nil
      url?:
        type: string | nil
  UpdateTodo:
    type: object
    additionalProperties: false
    properties:
      completed?:
        type: boolean | nil
      order?:
        type: order | nil
      title?:
        type: string | nil
  UpdateTodoViewModel:
    type: object
    additionalProperties: false
    properties:
      id?:
        type: string
      completed?:
        type: boolean
      order?:
        type: number
        format: int32
      title?:
        type: string | nil
      url?:
        type: string | nil
  CreateTodo:
    type: object
    additionalProperties: false
    properties:
      order?:
        type: number
        format: int32
      title?:
        type: string | nil
  errorMessages:
    type: array
    items: ValidationErrorViewModel
annotationTypes:
  amf-serverDescription:
    type: any
  amf-exclusiveMinimum:
    type: any
  amf-binding:
    type: any
  amf-pattern:
    type: any
  amf-payloads:
    type: any
  amf-exclusiveMaximum:
    type: any
  amf-consumes:
    type: any
  amf-additionalProperties:
    type: any
  amf-or:
    type: any
  amf-url:
    type: any
  amf-externalDocs:
    type: any
  amf-flow:
    type: any
  amf-oasDeprecated:
    type: any
  amf-contact:
    type: any
  amf-multipleOf:
    type: any
  amf-xor:
    type: any
  amf-not:
    type: any
  amf-callbacks:
    type: any
  amf-produces:
    type: any
  amf-format:
    type: any
  amf-license:
    type: any
  amf-summary:
    type: any
  amf-responses:
    type: any
  amf-maximum:
    type: any
  amf-tags:
    type: any
  amf-dependencies:
    type: any
  amf-readOnly:
    type: any
  amf-tuple:
    type: any
  amf-examples:
    type: any
  amf-collectionFormat:
    type: any
  amf-termsOfService:
    type: any
  amf-servers:
    type: any
  amf-xone:
    type: any
  amf-defaultResponse:
    type: any
  amf-baseUriParameters:
    type: any
  amf-parameters:
    type: any
  amf-minimum:
    type: any
  amf-recursive:
    type: any
  amf-and:
    type: any
title: ASP.NET Core WebAPI Starter
version: v1
/api/v1/todo:
  post:
    (amf-tags):
      - Todos
    body:
      application/json: CreateTodo
      text/json: CreateTodo
      application/*+json: CreateTodo
    responses:
      "422":
        description: Client Error
        body:
          text/plain: ValidationErrorsViewModel
          application/json: ValidationErrorsViewModel
          text/json: ValidationErrorsViewModel
      "500":
        description: Server Error
        body:
          text/plain: ErrorViewModel
          application/json: ErrorViewModel
          text/json: ErrorViewModel
      "200":
        description: Success
        body:
          text/plain: CreateTodoViewModel
          application/json: CreateTodoViewModel
          text/json: CreateTodoViewModel
  delete:
    (amf-tags):
      - Todos
    responses:
      "422":
        description: Client Error
        body:
          text/plain: ValidationErrorsViewModel
          application/json: ValidationErrorsViewModel
          text/json: ValidationErrorsViewModel
      "500":
        description: Server Error
        body:
          text/plain: ErrorViewModel
          application/json: ErrorViewModel
          text/json: ErrorViewModel
      "200":
        description: Success
        body:
          text/plain: CommandResultViewModel
          application/json: CommandResultViewModel
          text/json: CommandResultViewModel
  get:
    (amf-tags):
      - Todos
    queryParameters:
      Count?:
        type: boolean
      Filter?:
        type: string
      Limit?:
        type: number
        format: int32
      Order?:
        type: string
      Skip?:
        type: number
        format: int32
    responses:
      "422":
        description: Client Error
        body:
          text/plain: ValidationErrorsViewModel
          application/json: ValidationErrorsViewModel
          text/json: ValidationErrorsViewModel
      "500":
        description: Server Error
        body:
          text/plain: ErrorViewModel
          application/json: ErrorViewModel
          text/json: ErrorViewModel
      "200":
        description: Success
        body:
          application/json: GetTodoViewModelPagedResultViewModel
/api/v1/todo/{id}:
  delete:
    (amf-tags):
      - Todos
    (amf-baseUriParameters):
      id:
        required: true
        type: string
    responses:
      "422":
        description: Client Error
        body:
          text/plain: ValidationErrorsViewModel
          application/json: ValidationErrorsViewModel
          text/json: ValidationErrorsViewModel
      "500":
        description: Server Error
        body:
          text/plain: ErrorViewModel
          application/json: ErrorViewModel
          text/json: ErrorViewModel
      "200":
        description: Success
        body:
          text/plain: CommandResultViewModel
          application/json: CommandResultViewModel
          text/json: CommandResultViewModel
  get:
    (amf-tags):
      - Todos
    (amf-baseUriParameters):
      id:
        required: true
        type: string
    responses:
      "422":
        description: Client Error
        body:
          text/plain: ValidationErrorsViewModel
          application/json: ValidationErrorsViewModel
          text/json: ValidationErrorsViewModel
      "500":
        description: Server Error
        body:
          text/plain: ErrorViewModel
          application/json: ErrorViewModel
          text/json: ErrorViewModel
      "200":
        description: Success
        body:
          text/plain: GetTodoByIdViewModel
          application/json: GetTodoByIdViewModel
          text/json: GetTodoByIdViewModel
  patch:
    (amf-tags):
      - Todos
    body:
      application/json: UpdateTodo
      text/json: UpdateTodo
      application/*+json: UpdateTodo
    (amf-baseUriParameters):
      id:
        required: true
        type: string
    responses:
      "422":
        description: Client Error
        body:
          text/plain: ValidationErrorsViewModel
          application/json: ValidationErrorsViewModel
          text/json: ValidationErrorsViewModel
      "500":
        description: Server Error
        body:
          text/plain: ErrorViewModel
          application/json: ErrorViewModel
          text/json: ErrorViewModel
      "200":
        description: Success
        body:
          text/plain: UpdateTodoViewModel
          application/json: UpdateTodoViewModel
          text/json: UpdateTodoViewModel
