#%RAML 1.0 DataType

properties:
  id?:
    example: ""
    type: string
  completed?:
    type: boolean
  order?:
    type: number
    format: int32
  title?:
    type: string | nil
  url?:
    type: string | nil