#%RAML 1.0 DataType
title: GetTodoViewModel

properties:
  id?:
    example: "ec335d46-d575-47f9-a1f1-3e92e8aa616a"
    type: string
  completed?:
    example: false
    type: boolean
  order?:
    example: 1
    type: number
    format: int32
  title?:
    example: "Buy fruits"
    type: string | nil
  url?:
    example: ""
    type: string | nil