FROM mule-runner AS runner

FROM maven:3.9.9-eclipse-temurin-17-focal AS builder
WORKDIR /code
COPY pom.xml pom.xml
RUN mvn dependency:resolve

COPY --from=runner /app/mule /mule
ENV MULE_HOME=/mule
ENV MULE_BASE=/mule