services:

  db:
    image: todomvc-db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todomvc
    ports:
        - '5432:5432'

  adminer:
    image: adminer
    restart: always
    ports:
      - 9080:8080

  backend:
    image: todomvc-mule
    ports:
      - 8081:8081
